//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Natillera_Eventos_Parcial.Models
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;

    public partial class Evento
    {
        public int idEventos { get; set; }
        public int idAdministrador { get; set; }
        public string TipoEvento { get; set; }
        public string NombreEvento { get; set; }
        public int TotalIngreso { get; set; }
        public System.DateTime FechaEvento { get; set; }
        public string Sede { get; set; }
        public string ActividadesPlaneadas { get; set; }


        [JsonIgnore]  // 🛑 Evita el bucle al serializar
        public virtual Administrador Administrador { get; set; }
    }
}
